query Step($id: ID!) {
    step(where: { id: $id }) {
        id
        title
        description
        type
        videoUrl
        audioUrl
        question

        progress {
            id
            dateCompleted
        }

        note {
            id
            value
        }
    }
}