mutation updateCourseNote($courseID: ID!, $value: String!) {
  updateCourseNote(input:{courseID:$courseID, value:$value}) {
      id
      
      note {
        id
        courseID
        value
      }
  }
}