# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: yarn install
      - run: CI=true yarn test
      - run: yarn build
#   build_terraform:
#     steps:
#       - "cd /usr/bin"
#       - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip"
#       - "unzip -o terraform.zip"
#       - make validate-terraform APP_ENV=dev TERRAFORM_ACTION=plan
#       - make validate-terraform APP_ENV=management TERRAFORM_ACTION=plan

workflows:
  version: 2
  jobs:
    - build
    # - build_terraform