version: 0.2

env:
  variables:
    NODE_ENV: "${env}"
    CI: "true"

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - CI=true yarn test
      - yarn build
      - make validate-terraform APP_ENV=init TERRAFORM_ACTION=plan
      - make validate-terraform APP_ENV=dev TERRAFORM_ACTION=plan
      - make validate-terraform APP_ENV=management TERRAFORM_ACTION=plan

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'