version: 0.2

env:
  variables:
    NODE_ENV: "${env}"
    CI: "true"

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yarn install
      - CI=true yarn test
  build:
    commands:
      - yarn build

artifacts:
  files:
    - "**/*"
  name: "web-dist-${env}"
  base-directory: build

cache:
  paths:
    - /root/.npm/**/*