version: 0.2

env:
  variables:
    HTTPS: "true"
    CI: "true"
    HOST: "dev.mind.jdpx.co.uk"
    REACT_APP_BUILD_NUMBER: $CODEBUILD_BUILD_NUMBER
  parameter-store:
    REACT_APP_AUTH0_DOMAIN: "codebuild-auth-domain"
    REACT_APP_AUTH0_CLIENT_ID: "codebuild-auth0-client-id"
    REACT_APP_API_URL: "codebuild-api-url-dev"

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn lint
      - yarn test
      - yarn build

artifacts:
  files:
    - "**/*"
  name: "mind_hub_ui_build_artifact"
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'