query Course($id: ID!) {
    course(where: { id: $id }) {
        id
        title
        description

        note {
            id
            value
        }

        sessions {
            id
            title

            steps {
                id
                title

                progress {
                    id
                }
            }
        }

        progress {
            id
            dateStarted
        }
    }
}