query Course($id: ID!) {
    course(where: { id: $id }) {
        id
        title
        description

        note {
            id
            value
        }

        sessions {
            id
            title
        }

        progress {
            id
            started
        }
    }
}